# Generated by Django 3.1.7 on 2021-03-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('description', models.TextField(verbose_name='Descricao')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Inicio')),
                ('image', models.ImageField(upload_to='courses/images', verbose_name='Imagens')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
